//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClassDados.tnwsofthi {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicetnwSoap", Namespace="http://www.tnwsoftware.com.br/")]
    public partial class Servicetnw : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SegurancaClientes segurancaClientesValueField;
        
        private System.Threading.SendOrPostCallback uploadOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelRptOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelRptTesteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelCmdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelCmdZOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValcmdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProccmdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDistribuicaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback updStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback updVolOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHashOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servicetnw() {
            this.Url = global::ClassDados.Properties.Settings.Default.ClassDados_wsrv_Servicetnw;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SegurancaClientes SegurancaClientesValue {
            get {
                return this.segurancaClientesValueField;
            }
            set {
                this.segurancaClientesValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event uploadCompletedEventHandler uploadCompleted;
        
        /// <remarks/>
        public event downloadCompletedEventHandler downloadCompleted;
        
        /// <remarks/>
        public event SelRptCompletedEventHandler SelRptCompleted;
        
        /// <remarks/>
        public event SelRptTesteCompletedEventHandler SelRptTesteCompleted;
        
        /// <remarks/>
        public event SelCmdCompletedEventHandler SelCmdCompleted;
        
        /// <remarks/>
        public event SelCmdZCompletedEventHandler SelCmdZCompleted;
        
        /// <remarks/>
        public event ValcmdCompletedEventHandler ValcmdCompleted;
        
        /// <remarks/>
        public event ProccmdCompletedEventHandler ProccmdCompleted;
        
        /// <remarks/>
        public event getDistribuicaoCompletedEventHandler getDistribuicaoCompleted;
        
        /// <remarks/>
        public event updStatusCompletedEventHandler updStatusCompleted;
        
        /// <remarks/>
        public event updVolCompletedEventHandler updVolCompleted;
        
        /// <remarks/>
        public event getHashCompletedEventHandler getHashCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/upload", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string upload(string sArquivo, string sHash, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] bDados) {
            object[] results = this.Invoke("upload", new object[] {
                        sArquivo,
                        sHash,
                        bDados});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadAsync(string sArquivo, string sHash, byte[] bDados) {
            this.uploadAsync(sArquivo, sHash, bDados, null);
        }
        
        /// <remarks/>
        public void uploadAsync(string sArquivo, string sHash, byte[] bDados, object userState) {
            if ((this.uploadOperationCompleted == null)) {
                this.uploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadOperationCompleted);
            }
            this.InvokeAsync("upload", new object[] {
                        sArquivo,
                        sHash,
                        bDados}, this.uploadOperationCompleted, userState);
        }
        
        private void OnuploadOperationCompleted(object arg) {
            if ((this.uploadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadCompleted(this, new uploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/download", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] download(string sArquivo) {
            object[] results = this.Invoke("download", new object[] {
                        sArquivo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void downloadAsync(string sArquivo) {
            this.downloadAsync(sArquivo, null);
        }
        
        /// <remarks/>
        public void downloadAsync(string sArquivo, object userState) {
            if ((this.downloadOperationCompleted == null)) {
                this.downloadOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadOperationCompleted);
            }
            this.InvokeAsync("download", new object[] {
                        sArquivo}, this.downloadOperationCompleted, userState);
        }
        
        private void OndownloadOperationCompleted(object arg) {
            if ((this.downloadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadCompleted(this, new downloadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/SelRpt", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelRpt(string sReport, string[] sParamRpt) {
            object[] results = this.Invoke("SelRpt", new object[] {
                        sReport,
                        sParamRpt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelRptAsync(string sReport, string[] sParamRpt) {
            this.SelRptAsync(sReport, sParamRpt, null);
        }
        
        /// <remarks/>
        public void SelRptAsync(string sReport, string[] sParamRpt, object userState) {
            if ((this.SelRptOperationCompleted == null)) {
                this.SelRptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelRptOperationCompleted);
            }
            this.InvokeAsync("SelRpt", new object[] {
                        sReport,
                        sParamRpt}, this.SelRptOperationCompleted, userState);
        }
        
        private void OnSelRptOperationCompleted(object arg) {
            if ((this.SelRptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelRptCompleted(this, new SelRptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/SelRptTeste", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelRptTeste(string sReport, string sParam) {
            object[] results = this.Invoke("SelRptTeste", new object[] {
                        sReport,
                        sParam});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelRptTesteAsync(string sReport, string sParam) {
            this.SelRptTesteAsync(sReport, sParam, null);
        }
        
        /// <remarks/>
        public void SelRptTesteAsync(string sReport, string sParam, object userState) {
            if ((this.SelRptTesteOperationCompleted == null)) {
                this.SelRptTesteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelRptTesteOperationCompleted);
            }
            this.InvokeAsync("SelRptTeste", new object[] {
                        sReport,
                        sParam}, this.SelRptTesteOperationCompleted, userState);
        }
        
        private void OnSelRptTesteOperationCompleted(object arg) {
            if ((this.SelRptTesteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelRptTesteCompleted(this, new SelRptTesteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/SelCmd", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SelCmd(string sProc, string sParam) {
            object[] results = this.Invoke("SelCmd", new object[] {
                        sProc,
                        sParam});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SelCmdAsync(string sProc, string sParam) {
            this.SelCmdAsync(sProc, sParam, null);
        }
        
        /// <remarks/>
        public void SelCmdAsync(string sProc, string sParam, object userState) {
            if ((this.SelCmdOperationCompleted == null)) {
                this.SelCmdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelCmdOperationCompleted);
            }
            this.InvokeAsync("SelCmd", new object[] {
                        sProc,
                        sParam}, this.SelCmdOperationCompleted, userState);
        }
        
        private void OnSelCmdOperationCompleted(object arg) {
            if ((this.SelCmdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelCmdCompleted(this, new SelCmdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/SelCmdZ", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SelCmdZ(string sProc, string sParam) {
            object[] results = this.Invoke("SelCmdZ", new object[] {
                        sProc,
                        sParam});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void SelCmdZAsync(string sProc, string sParam) {
            this.SelCmdZAsync(sProc, sParam, null);
        }
        
        /// <remarks/>
        public void SelCmdZAsync(string sProc, string sParam, object userState) {
            if ((this.SelCmdZOperationCompleted == null)) {
                this.SelCmdZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelCmdZOperationCompleted);
            }
            this.InvokeAsync("SelCmdZ", new object[] {
                        sProc,
                        sParam}, this.SelCmdZOperationCompleted, userState);
        }
        
        private void OnSelCmdZOperationCompleted(object arg) {
            if ((this.SelCmdZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelCmdZCompleted(this, new SelCmdZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/Valcmd", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Valcmd(string sProc, string sParam) {
            object[] results = this.Invoke("Valcmd", new object[] {
                        sProc,
                        sParam});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValcmdAsync(string sProc, string sParam) {
            this.ValcmdAsync(sProc, sParam, null);
        }
        
        /// <remarks/>
        public void ValcmdAsync(string sProc, string sParam, object userState) {
            if ((this.ValcmdOperationCompleted == null)) {
                this.ValcmdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValcmdOperationCompleted);
            }
            this.InvokeAsync("Valcmd", new object[] {
                        sProc,
                        sParam}, this.ValcmdOperationCompleted, userState);
        }
        
        private void OnValcmdOperationCompleted(object arg) {
            if ((this.ValcmdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValcmdCompleted(this, new ValcmdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/Proccmd", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Proccmd(string sProc, string sParam) {
            object[] results = this.Invoke("Proccmd", new object[] {
                        sProc,
                        sParam});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProccmdAsync(string sProc, string sParam) {
            this.ProccmdAsync(sProc, sParam, null);
        }
        
        /// <remarks/>
        public void ProccmdAsync(string sProc, string sParam, object userState) {
            if ((this.ProccmdOperationCompleted == null)) {
                this.ProccmdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProccmdOperationCompleted);
            }
            this.InvokeAsync("Proccmd", new object[] {
                        sProc,
                        sParam}, this.ProccmdOperationCompleted, userState);
        }
        
        private void OnProccmdOperationCompleted(object arg) {
            if ((this.ProccmdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProccmdCompleted(this, new ProccmdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/getDistribuicao", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getDistribuicao(string sApp, string sData) {
            object[] results = this.Invoke("getDistribuicao", new object[] {
                        sApp,
                        sData});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getDistribuicaoAsync(string sApp, string sData) {
            this.getDistribuicaoAsync(sApp, sData, null);
        }
        
        /// <remarks/>
        public void getDistribuicaoAsync(string sApp, string sData, object userState) {
            if ((this.getDistribuicaoOperationCompleted == null)) {
                this.getDistribuicaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDistribuicaoOperationCompleted);
            }
            this.InvokeAsync("getDistribuicao", new object[] {
                        sApp,
                        sData}, this.getDistribuicaoOperationCompleted, userState);
        }
        
        private void OngetDistribuicaoOperationCompleted(object arg) {
            if ((this.getDistribuicaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDistribuicaoCompleted(this, new getDistribuicaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/updStatus", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updStatus(string sParam) {
            object[] results = this.Invoke("updStatus", new object[] {
                        sParam});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updStatusAsync(string sParam) {
            this.updStatusAsync(sParam, null);
        }
        
        /// <remarks/>
        public void updStatusAsync(string sParam, object userState) {
            if ((this.updStatusOperationCompleted == null)) {
                this.updStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdStatusOperationCompleted);
            }
            this.InvokeAsync("updStatus", new object[] {
                        sParam}, this.updStatusOperationCompleted, userState);
        }
        
        private void OnupdStatusOperationCompleted(object arg) {
            if ((this.updStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updStatusCompleted(this, new updStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/updVol", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updVol(string sParam) {
            object[] results = this.Invoke("updVol", new object[] {
                        sParam});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updVolAsync(string sParam) {
            this.updVolAsync(sParam, null);
        }
        
        /// <remarks/>
        public void updVolAsync(string sParam, object userState) {
            if ((this.updVolOperationCompleted == null)) {
                this.updVolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdVolOperationCompleted);
            }
            this.InvokeAsync("updVol", new object[] {
                        sParam}, this.updVolOperationCompleted, userState);
        }
        
        private void OnupdVolOperationCompleted(object arg) {
            if ((this.updVolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updVolCompleted(this, new updVolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SegurancaClientesValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.tnwsoftware.com.br/getHash", RequestNamespace="http://www.tnwsoftware.com.br/", ResponseNamespace="http://www.tnwsoftware.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getHash(string sApp, string sArquivo, string sData) {
            object[] results = this.Invoke("getHash", new object[] {
                        sApp,
                        sArquivo,
                        sData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getHashAsync(string sApp, string sArquivo, string sData) {
            this.getHashAsync(sApp, sArquivo, sData, null);
        }
        
        /// <remarks/>
        public void getHashAsync(string sApp, string sArquivo, string sData, object userState) {
            if ((this.getHashOperationCompleted == null)) {
                this.getHashOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHashOperationCompleted);
            }
            this.InvokeAsync("getHash", new object[] {
                        sApp,
                        sArquivo,
                        sData}, this.getHashOperationCompleted, userState);
        }
        
        private void OngetHashOperationCompleted(object arg) {
            if ((this.getHashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHashCompleted(this, new getHashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tnwsoftware.com.br/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.tnwsoftware.com.br/", IsNullable=false)]
    public partial class SegurancaClientes : System.Web.Services.Protocols.SoapHeader {
        
        private string usuarioField;
        
        private string senhaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void uploadCompletedEventHandler(object sender, uploadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void downloadCompletedEventHandler(object sender, downloadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SelRptCompletedEventHandler(object sender, SelRptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelRptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelRptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SelRptTesteCompletedEventHandler(object sender, SelRptTesteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelRptTesteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelRptTesteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SelCmdCompletedEventHandler(object sender, SelCmdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelCmdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelCmdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SelCmdZCompletedEventHandler(object sender, SelCmdZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelCmdZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelCmdZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValcmdCompletedEventHandler(object sender, ValcmdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValcmdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValcmdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ProccmdCompletedEventHandler(object sender, ProccmdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProccmdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProccmdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getDistribuicaoCompletedEventHandler(object sender, getDistribuicaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDistribuicaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDistribuicaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void updStatusCompletedEventHandler(object sender, updStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void updVolCompletedEventHandler(object sender, updVolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updVolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updVolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getHashCompletedEventHandler(object sender, getHashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591